# Generated by Django 3.1.2 on 2020-11-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20201104_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
